name: CI

on: [push, pull_request]

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v3.10.2
      env:
        VALIDATE_MD: false
        VALIDATE_CSS: false
        VALIDATE_JAVASCRIPT_STANDARD: false # TODO enable and configure eslint
        VALIDATE_RUBY: false # TODO enable and fix issues
